menu:
  Home: /
  Archives: /archives
  技术: /categories/tech
  生活: /categories/life
  随笔: /categories/casual
  项目: /categories/project

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# valine comment
valine: false
leancloud_id: 
leancloud_key: 

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: UA-143426112-1
